# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-27 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post_like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
