# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='postlikes', to='blog.User'),
        ),
    ]
